### ISSUE TITLE
Attempt to prepare 0.1.9 for release. Help needed

### ISSUE THREAD

**Issue by raysilent** [raysilent/lslforge#2]
0.1.7 branch (https://github.com/raysilent/lslforge/tree/0.1.7)

We should try to compile:
- Native components
- Eclipse modules (right now all `*.jar` files are just renamed to 0.1.7, so they are fake)

Our Eclipse update site URL attached to this branch will be https://raw.githubusercontent.com/raysilent/lslforge/0.1.7/eclipse/

**Comment by zauberparacelsus** [comment]
Will this release also include builds for Linux?

**Comment by Trapez** [comment]
I successfully built a linux version a few weeks ago. Will give 0.1.7 a try too.

**Comment by zauberparacelsus** [comment]
@Trapez Excellent to hear :+1:

**Comment by NeoBokrug** [comment]
Successfully built a windows version.

**Comment by Trapez** [comment]
It built fine on a clean 64 bit Xubuntu 15.10 with the following preparations:

sudo ln -s /usr/lib/x86_64-linux-gnu/libgmp.so.10.2.0 /usr/lib/x86_64-linux-gnu/libgmp.so.3

sudo apt-get install libgmp3-dev

**Comment by raysilent** [comment]
That's great. Any ideas how to combine all that into final release? Mac is a must too.

**Comment by Trapez** [comment]
A new update site with 64bit windows and linux versions would be a good start. Mac version to follow when someone builds it.

Linux x64:
https://www.dropbox.com/s/gsxmoh02h0sfwx7/LSLForge?dl=0

**Comment by RayZopf** [comment]
any idea how cross-compilation works on Windows?
as GHC 6.10.1 (or [6.10.4](https://www.haskell.org/ghc/download_ghc_6_10_4#windows) that I use) only provide a x86 build environment  
7.6.1 seems to be the first one with [native x86_64 GHC](https://ghc.haskell.org/trac/ghc/wiki/WindowsGhc), but does this work with the ancient packages that LSLForge haskell code uses?

**Comment by KoolLSL** [comment]
I will gladly test a 64bit Windows on few thousands lines if the .exe is available via update. I haven't time to build it myself now

**Comment by raysilent** [comment]
Thank you guys, trying to figure out how to pack them into plugin *.jar(s)

**Comment by zauberparacelsus** [comment]
Bump?

**Comment by mthome** [comment]
status?  AFAIK, all the old update sites are unusable due to refs to googlecode.  I can help out if needed.  I haven't had any luck getting more recent GHCs to build the ancient packages... nor have I had much luck converting the old code to use newer haskell-platform packages (IIRC, fclabels had a near complete reimplementation and I'm not enough of a haskell hacker to grok the intent of the original code).

**Comment by raysilent** [comment]
Everyone who has offered help with Mac and Linux, please recompile your binary files against [0.1.9 ](https://github.com/raysilent/lslforge/tree/0.1.9) branch and make pull requests against that branch
- Rename the "dist" folder to "dist_temp" so it could be committed
- Please don't forget to `$ strip executable`

Thank you!
