### ISSUE TITLE
LSLforge does not recognize multiline strings

### ISSUE THREAD

**Issue by RayZopf** [raysilent/lslforge#26]
https://code.google.com/archive/p/lslforge/issues/49  
Posted on Jul 2, 2014 by Grumpy Hippo
The script below is valid LSL. However, LSLforge throws an error because it does recognize multi-line strings. This appears to be an oversight, as it allows vectors, rotations, lists, and function arguments to span multiple lines. For right now, I'm writing out the multiline string as a list of strings within a call to llDumpList2String() with "\n" as the separator.

default { state_entry() { llSay(0, "testing... 1... 2... 3... Whiskey Tango Foxtrot"); } }  
https://code.google.com/archive/p/lslforge/issues/8  

Posted on Jan 18, 2012 by Happy Giraffe
Editor doesn't obey color for multi-line comments

**Comment by raysilent** [comment]
For the editor not obeying color we may create another issue
