### ISSUE TITLE
LSLForge compiles lslp to lsl much too often even without code changes

### ISSUE THREAD

**Issue by RayZopf** [raysilent/lslforge#29]
https://code.google.com/archive/p/lslforge/issues/41  
Posted on Mar 31, 2014 by Happy Wombat
What steps will reproduce the problem? 1. closeEclipse with a lslp left open / reopen Eclipse 2. find LSL Forge evaluate lslp code that was open last time Eclipse was closed 3. look at the optimized lsl that got refreshed+timestamped

What is the expected output? What do you see instead? no recompiled of lsl when there are no changes instead most of the code gets recompiled just to have a changed first comment line stating compile date

What version of the product are you using? On what operating system? LSLForge 0.16 patched, Eclipse Kepler, Java 1.6

Please provide any additional information below. see https://code.google.com/p/lslforge/issues/detail?id=3#c12 this is a pita with Git...

Comment 1

Posted on Mar 31, 2014 by Happy Wombat
same when just opening a lslp that has an already compiled lsl - only opening and viewing code should not alter files in a way that git sees differences

I know, changes of modules are a critical point - but then it would be better to have some additional info or popup to request recompile. What if I want to keep the 'old' lsl instead of making use of a modified module...

**Comment by PellSmit** [comment]
I fixed it 3 years ago, at commit 210bb12.
Is it time to close this issue?

**Comment by raysilent** [comment]
Nice! I'll close this then! Thank you @PellSmit, you are the best!
