### ISSUE TITLE
Preparing for 0.1.9 release

### ISSUE THREAD

**Issue by Corysia** [raysilent/lslforge#31]
An error occurred while collecting items to be installed
session context was:(profile=_Users_corysia_eclipse_cpp-neon_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_linux_x86_plugin_0.1.8.jar.
https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_linux_x86_plugin_0.1.8.jar
Artifact not found: https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_linux_x86_64_plugin_0.1.8.jar.
https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_linux_x86_64_plugin_0.1.8.jar
Artifact not found: https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_macosx_x86_plugin_0.1.8.jar.
https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_macosx_x86_plugin_0.1.8.jar
Artifact not found: https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_part_linux_x86_feature_0.1.8.jar.
https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_part_linux_x86_feature_0.1.8.jar
Artifact not found: https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_part_linux_x86_64_feature_0.1.8.jar.
https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_part_linux_x86_64_feature_0.1.8.jar
Artifact not found: https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_part_macosx_x86_feature_0.1.8.jar.
https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_part_macosx_x86_feature_0.1.8.jar

**Comment by raysilent** [comment]
Everyone who has offered help with Mac and Linux, please recompile your binary files against [0.1.9 ](https://github.com/raysilent/lslforge/tree/0.1.9) branch and make pull requests against that branch
- Rename the "dist" folder to "dist_temp" so it could be committed
- Please don't forget to `$ strip executable`

Thank you!

**Comment by Corysia** [comment]
I've access to Mac and Linux systems, but I don't know how to build the project.  Otherwise, I'd be happy to create the images.

**Comment by Trapez** [comment]
Linux x86_64: https://dl.dropboxusercontent.com/u/94956164/LSLForge

As it stands now I'm not sure I get everything installed from the update site since it ends in this error message on linux/eclipse neon:

An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_linux_x86_64_plugin_0.1.8.jar.
https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_linux_x86_64_plugin_0.1.8.jar
Artifact not found: https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_part_linux_x86_64_feature_0.1.8.jar.
https://github.com/raysilent/lslforge/raw/master/eclipse/lslforge_part_linux_x86_64_feature_0.1.8.jar

**Comment by Corysia** [comment]
That would be because the jars haven't been built yet and uploaded to github.  Only the Windows distribution has been built.  That's what Ray is asking for: for the volunteers to build the jars from the source and make a pull request in to the project so that they can be made available for installation.

**Comment by raysilent** [comment]
@Trapez Please confirm you compiled the 0.1.9 branch

**Comment by Trapez** [comment]
I just cloned https://github.com/raysilent/lslforge.git and compiled it.

**Comment by Trapez** [comment]
New compile: https://dl.dropboxusercontent.com/u/94956164/LSLForge
This time I cloned this way: git clone https://github.com/raysilent/lslforge.git --branch 0.1.9 --single-branch
That gives me: runhaskell Setup.hs configure
Configuring LSLForge-0.1.9...

Looks better.

**Comment by raysilent** [comment]
Waiting for Mac now. Thank you @Trapez

**Comment by raysilent** [comment]
@Trapez We need you again, to repeat the same, 0.1.9 has changed due to 1 more constant missing (CLICK_ACTION_ZOOM)

**Comment by Trapez** [comment]
New build: https://dl.dropboxusercontent.com/u/94956164/LSLForge

**Comment by raysilent** [comment]
Thank you @Trapez 

Please test it out!
I'm not sure if we are able to download it with anything lower than **Eclipse Neon**

**Comment by zauberparacelsus** [comment]
New LSLforge is NOT playing nice.  I'm getting a "unable to create native thread" error during the rebuilding outline step, and I also saw an out-of-memory error as well.

**Comment by Trapez** [comment]
I just did some very brief testing of 0.1.9 on both win32 eclipse neon and linux x64 eclipse neon and it looks fine so far.

**Comment by zauberparacelsus** [comment]
@Trapez Is Neon a newer version of Eclipse?  I'm still on Mars.2, which AFAIK is what Ubuntu 16.04 has in its repo.

**Comment by zauberparacelsus** [comment]
Okay, the new LSLforge seems to work fine with Eclipse Neon.  With Eclipse Mars, however, it just breaks.

**Comment by raysilent** [comment]
Thank you for all your reports! I'll try to build it using Eclipse Juno and we'll test it out
