### ISSUE TITLE
0.1.9.1 release

### ISSUE THREAD

**Issue by raysilent** [raysilent/lslforge#38]
@Trapez we need you with Linux again!

```
git clone https://github.com/raysilent/lslforge.git --branch 0.1.9.1 --single-branch
```

**Comment by raysilent** [comment]
@PellSmit Apperantly, we need to recompile the code again so it combines both fixes that you made (#39 and #40) while keeping what was introduced in the 0.1.9.1 branch. It seems that the binary we have at the moment fixes #40 but not the #39.

Please pull it again from 

```
git clone https://github.com/raysilent/lslforge.git --branch 0.1.9.1 --single-branch
```

compile and pull request toward 0.1.9.1 branch.

Thank you

**Comment by raysilent** [comment]
Thank you Pell

**Comment by raysilent** [comment]
@Trapez We need your binary module!

**Comment by Trapez** [comment]
Here. https://dl.dropboxusercontent.com/u/94956164/LSLForge

**Comment by raysilent** [comment]
Thank you @Trapez!
