### ISSUE TITLE
0.1.9.2 help wanted

### ISSUE THREAD

**Issue by raysilent** [raysilent/lslforge#42]
Guys (@Trapez, @PellSmit), we need help compiling Linux and Mac executables

Please use the following branch:
```
git clone https://github.com/raysilent/lslforge.git --branch 0.1.9.2 --single-branch
```

**Comment by raysilent** [comment]
Thank you @PellSmit!
Would you be able to test out plugin update using the [link](https://raw.githubusercontent.com/raysilent/lslforge/0.1.9.2/eclipse/)? I assume adding it as additional plugin source should work just fine.

**Comment by PellSmit** [comment]
You are welcome, Ray.
It seems fine on El Capitan & Eclipse Neon.

**Comment by raysilent** [comment]
@Trapez, any success?

**Comment by Trapez** [comment]
Finally 0.1.9.2: https://dl.dropboxusercontent.com/u/94956164/LSLForge

**Comment by raysilent** [comment]
Thank you Trapez!
