### ISSUE TITLE
0.1.9.3 help wanted

### ISSUE THREAD

**Issue by raysilent** [raysilent/lslforge#44]
Guys (@Trapez, @PellSmit), we need help compiling Linux and Mac executables to fix a typo.

Please use the following branch:

```
git clone https://github.com/raysilent/lslforge.git --branch 0.1.9.3 --single-branch
```

**Comment by raysilent** [comment]
Awesome, thank you @PellSmit!

**Comment by PellSmit** [comment]
yw @raysilent

**Comment by Trapez** [comment]
0.1.9.3:https://dl.dropboxusercontent.com/u/94956164/LSLForge



    On Tuesday, February 7, 2017 4:59 PM, Ray Silent <notifications@github.com> wrote:
 

 Guys (@Trapez, @PellSmit), we need help compiling Linux and Mac executables to fix a typo.Please use the following branch:git clone https://github.com/raysilent/lslforge.git --branch 0.1.9.3 --single-branch
