### ISSUE TITLE
Returning void value(function) when optimization enabled kills LSLForge process

### ISSUE THREAD

**Issue by PellSmit** [raysilent/lslforge#55]
///////////////////////////////
func()
{
	return func1();
}

// pragma inline
func1()
{
	;
}
/////////////////////////////

Above code kills LSLForge process at optimization enabled,
no error at optimization disabled.

It will be fixed at 0.1.9.7.

**Comment by raysilent** [comment]
Is it fixed now @PellSmit ?

**Comment by PellSmit** [comment]
I fixed it at https://github.com/elnewfie/lslforge/commit/f7593ab021eb4bad2f7a0863144f07e566b5f51e

**Comment by raysilent** [comment]
Oh alright. I think it's been merged then
