### ISSUE TITLE
Global string variables with backslashes get doubled in .lsl

### ISSUE THREAD

**Issue by NeoBokrug** [raysilent/lslforge#6]
.lslm  :

'string bad_string  = "/\/\onies!";

default {
    state_entry() {
        llOwnerSay(bad_string);
    }
}'

.lsl :

'string bad_string = "/\/\onies!";  // Heh, it's not showing in the comment, but trust me.

default {

```
state_entry() {
    llOwnerSay(bad_string);
}
```

}'

**Comment by raysilent** [comment]
Hey would you attach the file, it's obviously garbled here

**Comment by NeoBokrug** [comment]
[bad_test.lsl.txt](https://github.com/raysilent/lslforge/files/145361/bad_test.lsl.txt)
[bad_test.lslp.txt](https://github.com/raysilent/lslforge/files/145362/bad_test.lslp.txt)

**Comment by RayZopf** [comment]
also mentioned in https://code.google.com/archive/p/lslforge/issues/18 comment 4

> Posted on Aug 1, 2012 by Grumpy Bird
> Same/similar issue?
> 
> The string literal "\;" normally becomes just ; when compiled and run in SL but LSLForge changes it in the .lsl to "\;" which becomes \; in SL, altering script behavior.
> 
> Easy to avoid, but took me a while to figure out what's going on
